### ISSUE TITLE
Add tests / documentation for release tool

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/dockerfiles#72]

**Comment by kenoir** [comment]
The release tool would probably do better being extracted to its own repo - and then pulled in here when wrapped in a container.

**Comment by jamesgorrie** [comment]
Do we want to give it a fancy name?
e.g. [serpentine](https://www.google.com/search?q=serpentine+belt+tool&tbm=isch&source=hp&safe=off&sa=X&ved=2ahUKEwie74mots3jAhWSUBUIHc5FALAQsAR6BAgFEAE&biw=1920&bih=1066)?

**Comment by alexwlchan** [comment]
Closing as stale; we no longer use weco-deploy.
